### ISSUE TITLE
interesting...

### ISSUE THREAD

**Issue by StarFscker** [kanej/Posh-Cowsay#13]
PS C:\WINDOWS\system32> cowsay some things that are to be said

---

< System.Object[] >

---

```
  \  ^__^             
   \ (oo)\________    
     (__)\        )\/\
          ||----w |   
          ||     ||   
```

PS C:\WINDOWS\system32> echo "This is a test " | cowsay

---

< System.Object[]  This  is  a  test >

---

```
  \  ^__^             
   \ (oo)\________    
     (__)\        )\/\
          ||----w |   
          ||     ||   
```

I'm looking for the cause right now...

**Comment by robianmcd** [comment]
same problem here

**Comment by kanej** [comment]
Sorry for taking so long to get back. The issue was posh-cowsay was relying on some array behaviour that changed with powershell 3.0 (arrays in posh will never cease to be a source of surprise for me). It should be fixed now if you want to give it a try.

**Comment by StarFscker** [comment]
Thanks, I'll try it when in at work.
